name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE: ./Azure.Monitor.Telemetry.csproj
  # Path to the test results directory relative to the root of the project.
  TEST_RESULTS_DIRECTORY: ${{ github.workspace }}/TestResults

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Test
      id: test1
      continue-on-error: true
      run: dotnet test ${{ env.SOLUTION_FILE }} --framework net9.0 --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --results-directory ${{ env.TEST_RESULTS_DIRECTORY }} --logger:"console;verbosity=detailed" --logger:"trx;logfileprefix=testResults_" -filter TestCategory==UnitTests
