name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE: ./Azure.Monitor.Telemetry.sln
  # Path to the test results directory relative to the root of the project.
  TEST_RESULTS_DIRECTORY: ./testsResults

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore Src
      run: dotnet restore ./src/Azure.Monitor.Telemetry.csproj
      
    - name: Restore Tests
      run: dotnet restore ./tests/Azure.Monitor.Telemetry.Tests.csproj --no-dependencies

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Run Tests
      id: UnitTests
      run: dotnet test ${{ env.SOLUTION_FILE }} --framework net9.0 --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --results-directory ${{ env.TEST_RESULTS_DIRECTORY }} --logger:"console;verbosity=detailed" --logger:"trx;logfileprefix=testResults_" --filter TestCategory=UnitTests

    - name: Publish Tests Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always()
      with:
        files: |
          ${{ env.TEST_RESULTS_DIRECTORY }}\**\*.trx
  