name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE: ./Azure.Monitor.Telemetry.sln
  # Path to the test results directory relative to the root of the project.
  TESTS_RESULTS_DIRECTORY: ./testsResults
  # Verbosity level
  VERBOSITY: minimal

permissions:
  checks: write
  pull-requests: write

jobs:
  Run:
    runs-on: windows-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: Restore
      run: >-
        dotnet restore ${{ env.SOLUTION_FILE }}
        --verbosity ${{ env.VERBOSITY }}

    - name: Build
      run: >-
        dotnet build ${{ env.SOLUTION_FILE }}
        --configuration ${{ env.BUILD_CONFIGURATION }}
        --no-restore
        --verbosity ${{ env.VERBOSITY }}

    - name: Test
      id: UnitTests
      run: >-
        dotnet test ${{ env.SOLUTION_FILE }}
        --collect:"XPlat Code Coverage"
        --configuration ${{ env.BUILD_CONFIGURATION }}
        --filter TestCategory=UnitTests
        --framework net9.0
        --logger:"trx"
        --no-build
        --results-directory ${{ env.TESTS_RESULTS_DIRECTORY }}
        --verbosity ${{ env.VERBOSITY }}

    - name: Report Tests Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always()
      with:
        files: |
          ${{ env.TESTS_RESULTS_DIRECTORY }}/**/*.trx

    - name: Produce the coverage report
      uses: insightsengineering/coverage-action@v2
      if: always()
      with:
        # Path to the Cobertura XML report.
        path: ${{ env.TESTS_RESULTS_DIRECTORY }}/**/coverage.cobertura.xml
        # Minimum total coverage
        threshold: 95
        # Fail the workflow if the code coverage is below the threshold
        fail: true
        # Title of the code coverage summary
        coverage-summary-title: "Code Coverage Summary"
