# The workflow to test azure integration

name: Check

on:
  workflow_dispatch:

jobs:
  run:
    name: Run

    permissions:
      contents: read
      # Required by azure/login action
      id-token: write

    runs-on: windows-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.ENTRA_APP_CLIENT_ID }}
        tenant-id: ${{ vars.ENTRA_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTIONS_DEV_ID }}