# The workflow to test azure integration

name: Test Azure

on:
  workflow_dispatch:

jobs:
  run:
    env:
      AZURE_DATACENTER_NAME: eastus
      AZURE_RESOURCE_GROUP_NAME: test

    name: Run

    permissions:
      contents: read
      # Required by azure/login action
      id-token: write

    runs-on: windows-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.ENTRA_APP_CLIENT_ID }}
        tenant-id: ${{ vars.ENTRA_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTIONS_DEV_ID }}

    - name: Create Resource Group
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az group create -l ${{ env.AZURE_DATACENTER_NAME }} -n ${{ env.AZURE_RESOURCE_GROUP_NAME }}

    - name: Create Resource Group
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az group delete -n ${{ env.AZURE_RESOURCE_GROUP_NAME }} -y
