# The workflow to publish NuGet package to nuget.org

name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: pack
        path: ./artifact

    - name: Unzip artifact
      run: unzip ./artifact/package.zip -d ./push

    - name: Publish to NuGet
      run: >-
        dotnet nuget push ./push/*.nupkg
        --api-key ${{ secrets.NUGET_API_KEY }}
        --source https://api.nuget.org/v3/index.json
