# The workflow to release the library.
# The workflow allows to include different steps in the process:
# - Attest the package provenance
# - Release the package to github.com Feed
# - Release the package to nuget.org Feed
# - Create a GitHub Release

name: Release

on:
  workflow_dispatch:
    inputs:
      id:
        default: 'Stas.Azure.Monitor.Telemetry'
        description: Identifier
        required: true
        type: string
      version:
        description: Version in format X.Y.Z
        required: true
        type: string
      isPreRelease:
        default: false
        description: Is Pre-Release
        required: false
        type: boolean
      attestProvenance:
        default: false
        description: Attest Provenance
        required: true
        type: boolean
      pushToGitHub:
        default: false
        description: Push to GitHub.com
        required: true
        type: boolean
      pushToNuGet:
        default: false
        description: Push to NuGet.org
        required: true
        type: boolean
      createRelease:
        default: false
        description: Create a Release
        required: true
        type: boolean

run-name: ${{ format('{0}.{1}{2}', inputs.id, inputs.version, inputs.isPreRelease && '-rc' || '') }}

jobs:
  run:
    name: Run

    permissions:
      # Required by Attestation action to persist the attestation
      attestations: write
      # Required to create a release on GitHub
      contents: write
      # Required by Attestation action to mint the OIDC token necessary to request a Sigstore signing certificate
      id-token: write
      # Required to push the package to GitHub
      packages: write

    # one of target frameworks is net462
    runs-on: windows-latest

    env:
      # Assembly Sign Certificate
      ASSEMBLY_SIGN_CERTIFICATE_FILE_NAME: 'assembly.snk'
      # Configuration type to build.
      BUILD_CONFIGURATION_NAME: Release
      # Path to the project file relative to the root of the project.
      MAIN_PROJECT_FILE_PATH: .\src\Azure.Monitor.Telemetry.csproj
      # Package identifier
      PACKAGE_ID: ${{ inputs.id }}
      # Package output directory path
      PACKAGE_OUTPUT_DIRECTORY_PATH: .\out
      # Package Version
      PACKAGE_VERSION: ${{ format('{0}{1}', inputs.version, inputs.isPreRelease && '-rc' || '') }}
      # Repo url
      REPO_URL: ${{ format('{0}/{1}', github.server_url, github.repository) }}
      # Verbosity level
      VERBOSITY: quiet

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

      # this is bash, this is why slashes should '/'
    - name: Get Sign Certificate
      run: |
        echo -n $ASSEMBLY_SIGN_CERTIFICATE_SNK_BASE64 | base64 -d >> ./src/${{ env.ASSEMBLY_SIGN_CERTIFICATE_FILE_NAME }}
      shell: bash
      env:
        ASSEMBLY_SIGN_CERTIFICATE_SNK_BASE64: ${{ secrets.ASSEMBLY_SIGN_CERTIFICATE_SNK_BASE64 }}

    - name: Pack Project
      run: >-
        dotnet pack ${{ env.MAIN_PROJECT_FILE_PATH }}
        --configuration ${{ env.BUILD_CONFIGURATION_NAME }}
        --output ${{ env.PACKAGE_OUTPUT_DIRECTORY_PATH }}
        --verbosity ${{ env.VERBOSITY }}
        -p:AssemblyOriginatorKeyFile=${{ env.ASSEMBLY_SIGN_CERTIFICATE_FILE_NAME }}
        -p:AssemblyVersion=${{ inputs.version }}
        -p:PackageId=${{ env.PACKAGE_ID }}
        -p:PackageProjectUrl=${{ env.REPO_URL }}
        -p:PackageVersion=${{ env.PACKAGE_VERSION }}
        -p:RepositoryBranch=${{ github.ref_name }}
        -p:RepositoryCommit=${{ github.sha }}
        -p:RepositoryUrl=${{ env.REPO_URL }}

    - name: Attest Provenance
      if: ${{ inputs.attestProvenance }}
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ${{ env.PACKAGE_OUTPUT_DIRECTORY_PATH }}\*.*pkg

    - name: Configure GitHub NuGet Feed
      if: ${{ inputs.pushToGitHub }}
      uses: actions/setup-dotnet@v4
      with:
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
    - name: Push Package to GitHub
      if: ${{ inputs.pushToGitHub }}
      run: >-
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY_PATH }}\*.nupkg

    - name: Push Package to NuGet
      if: ${{ inputs.pushToNuGet }}
      run: >-
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY_PATH }}\*.nupkg
        --api-key ${{ secrets.NUGET_API_KEY }}
        --source ${{ vars.NUGET_API_URL }}

    - name: Create Release
      if: ${{ inputs.createRelease }}
      run: >-
        gh release create "v${{ env.PACKAGE_VERSION }}"
        --generate-notes
        --prerelease="${{ inputs.isPreRelease }}"
        --repo="${{ github.repository }}"
        --target="${{ github.sha }}"
        --title="${{env.PACKAGE_ID}}.${{ env.PACKAGE_VERSION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
